[build]
  base = "."  # Repo root (correct)
  command = "cd netlify/functions && npm install && cd ../frontend && rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = "frontend/dist"  # Correct
  functionsDirectory = "netlify/functions"  # Correct

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"  # Safer than --force

# Opt-out secrets scanning for VITE_TMDB_API_KEY (if still needed)
SECRETS_SCAN_OMIT_KEYS = "VITE_TMDB_API_KEY"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200