[build]
  base = "."  # Start from repo root (fixes path resolution)
  command = "cd netlify/functions && npm install && cd frontend && rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = "frontend/dist"  # Now resolves correctly to /opt/build/repo/frontend/dist
  functionsDirectory = "netlify/functions"  # Standard key; resolves to root-level

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"  # Safer than --force; handles peer dep conflicts

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
