[build]
  base = "."  # Repo root
  command = "cd netlify/functions && npm install && cd ../../frontend && rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = "frontend/dist"
  functionsDirectory = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

SECRETS_SCAN_OMIT_KEYS = "VITE_TMDB_API_KEY"  # If needed

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200