[build]
  command = "cd netlify/functions && npm install && cd ../../frontend && rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = "frontend/dist"
  functions = "netlify/functions"
  base = "frontend"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--force"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

