[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "dist"
  environment = { 
    VITE_API_URL = "https://movie-app-n6iv.onrender.com",
    VITE_TMDB_API_KEY = "52ec3563e14900d11681ced3bf093f1d"
  }

[[redirects]]
  from = "/api/*"
  to = "https://movie-app-n6iv.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200